<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="8" hostname="AFSWWL0S8LVCKO" failures="1" tests="1" name="Default test" time="0.753" errors="0" timestamp="2023-03-09T13:54:39 CST">
  <testcase classname="com.org.OhIForgotProvider.service.TaskServiceTest" name="whenSaveTask_returnTask" time="0.026">
    <failure type="java.lang.AssertionError" message="expected [Task(id=1, description=Get groceries, dueDate=2023-03-09, user=null)] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [Task(id=1, description=Get groceries, dueDate=2023-03-09, user=null)] but found [null]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:617)
at com.org.OhIForgotProvider.service.TaskServiceTest.whenSaveTask_returnTask(TaskServiceTest.java:142)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:239)
at org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:186)
at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:253)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:594)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- whenSaveTask_returnTask -->
  <testcase classname="com.org.OhIForgotProvider.service.TaskServiceTest" name="whenRetrievingList_ShowsNoTask" time="0.0">
    <ignored/>
  </testcase> <!-- whenRetrievingList_ShowsNoTask -->
  <testcase classname="com.org.OhIForgotProvider.service.TaskServiceTest" name="whenUpdating_DescriptionIsBlank_ReturnsNull" time="0.0">
    <ignored/>
  </testcase> <!-- whenUpdating_DescriptionIsBlank_ReturnsNull -->
  <testcase classname="com.org.OhIForgotProvider.service.TaskServiceTest" name="whenGivenId_DeleteTask" time="0.0">
    <ignored/>
  </testcase> <!-- whenGivenId_DeleteTask -->
  <testcase classname="com.org.OhIForgotProvider.service.TaskServiceTest" name="whenUpdatingTask_ReturnsUpdatedTask" time="0.0">
    <ignored/>
  </testcase> <!-- whenUpdatingTask_ReturnsUpdatedTask -->
  <testcase classname="com.org.OhIForgotProvider.service.TaskServiceTest" name="descriptionEmpty_CannotSaveTask" time="0.0">
    <ignored/>
  </testcase> <!-- descriptionEmpty_CannotSaveTask -->
  <testcase classname="com.org.OhIForgotProvider.service.TaskServiceTest" name="whenListIsCalled_ShowsListOfTasks" time="0.0">
    <ignored/>
  </testcase> <!-- whenListIsCalled_ShowsListOfTasks -->
  <testcase classname="com.org.OhIForgotProvider.service.TaskServiceTest" name="whenGivenId_returnsTask" time="0.0">
    <ignored/>
  </testcase> <!-- whenGivenId_returnsTask -->
  <testcase classname="com.org.OhIForgotProvider.service.TaskServiceTest" name="whenGivenId_ReturnsNull" time="0.0">
    <ignored/>
  </testcase> <!-- whenGivenId_ReturnsNull -->
</testsuite> <!-- Default test -->
